// <auto-generated />
namespace Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inital_Version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inital_Version));
        
        string IMigrationMetadata.Id
        {
            get { return "201712012204457_Inital_Version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
